In [2]:
import numpy as np

# Não confundir
    np.arange(0, 10, 3) -> o 3 é o step

    np.linspace(0, 10, 3) -> o 3 é o nº de elementos

In [2]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [3]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# valor randômico tirado de uma distribuição normal padrão N(0, 1) -> média=0, var=1
# como é normal pradrão, os valores não estão limitados a [-1, 1]
np.random.randn(2,4)

array([[-0.42442996, -1.27612979,  1.01133276, -0.98112076],
       [-1.36065771,  0.21061685, -0.06423917, -0.1035857 ]])

In [8]:
#algumas funções exigem que você passe o tamanho da matriz/vetor por tupla, outras não exiem isso
np.random.randint(0, 100, (2, 3))

array([[94, 83, 62],
       [82, 88, 25]])

In [9]:
arr = np.arange(0, 50)

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [11]:
arr.reshape(5, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

# Diferença importante entre lista x np array
    qualquer mudança num slice de um array reflete na array original
    isso não acontece em uma lista normal do python
    EM SUMA: um slice de um array não é uma cópia daquele pedaço, mas apenas uma view da array completa
    se você quiser uma cópia, use copia_da_array = array.copy()

In [12]:
# Lista python normal
teste = [0, 1,2,3, 4, 5, 6, 7, 8, 9]

In [13]:
a = teste[0:6]

In [14]:
a = [1, 1, 1, 1, 1]

In [15]:
teste

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
# array NumPy
teste_np = np.arange(0, 10)

In [17]:
slice_teste = teste_np[0:6]

In [18]:
slice_teste[:] = 5

In [19]:
teste_np

array([5, 5, 5, 5, 5, 5, 6, 7, 8, 9])

In [20]:
a = teste_np[8:9]

In [21]:
a

array([8])

In [22]:
a[:] = 9999

In [23]:
teste_np

array([   5,    5,    5,    5,    5,    5,    6,    7, 9999,    9])

In [24]:
copia = teste_np.copy()

In [25]:
copia[:] = 0

In [26]:
copia

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
teste_np

array([   5,    5,    5,    5,    5,    5,    6,    7, 9999,    9])

## pegando um pedaço de uma matriz

In [28]:
matriz = np.random.rand(5, 5)
matriz

array([[0.62659205, 0.94652062, 0.49127525, 0.81129605, 0.37227127],
       [0.19275355, 0.44005393, 0.13345161, 0.56055266, 0.07204338],
       [0.40179694, 0.1347724 , 0.19748521, 0.04950028, 0.49527293],
       [0.27485337, 0.54408185, 0.59005923, 0.48261489, 0.33107991],
       [0.61008305, 0.32105622, 0.20230844, 0.1427638 , 0.72067217]])

In [29]:
matriz[:3, :3]

array([[0.62659205, 0.94652062, 0.49127525],
       [0.19275355, 0.44005393, 0.13345161],
       [0.40179694, 0.1347724 , 0.19748521]])

In [30]:
matriz[3:, 3:]

array([[0.48261489, 0.33107991],
       [0.1427638 , 0.72067217]])

# Seleção condicional em um Array
    se parece com o filter em Listas
    você cria uma condicional que retorna booleano
    e depois usa para filtrar valores

In [38]:
arr = np.arange(0, 11)

In [40]:
arr[arr%3==0]

array([0, 3, 6, 9])

## relembando do filter

In [41]:
minha_lista = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
list(filter(lambda num:num%3==0, minha_lista))

[0, 3, 6, 9]

# OPERAÇÕES
comparando lista com array 

In [45]:
a = list[1, 2, 2,3, 4, 5]

In [48]:
# isso aqui não funciona com listas:
# a + a

In [49]:
# mas funciona com arrays
arr = np.arange(0, 11)
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [50]:
arr*4

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [51]:
np.append(arr, arr) #coloca os elementos no final da array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  0,  1,  2,  3,  4,  5,
        6,  7,  8,  9, 10])

# Importante entender o insert do numpy

In [40]:
arr_2 = np.arange(0,10).reshape(2,5)
arr_2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [41]:
np.insert(arr, 11, 2000, axis=0)
# no insert, você precisa especificar o index do dado inserido
# e essa operação não é persistente

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
       2000])

In [46]:
## este insert ajuda a entender bem o argumento 'axis'

np.insert(arr_2, 1, [999, 888], axis=1) 

array([[  0, 999,   1,   2,   3,   4],
       [  5, 888,   6,   7,   8,   9]])

In [47]:
np.insert(arr_2, 1, 999, axis=0)

array([[  0,   1,   2,   3,   4],
       [999, 999, 999, 999, 999],
       [  5,   6,   7,   8,   9]])

# Universal Operarions or Functions
    ufunc
    https://numpy.org/doc/stable/reference/ufuncs.html